"""
render_research.py
Generates docs/research.html — ENSO Research Intelligence page.
Reads dashboard_historical.json (generated by the local RAG pipeline).
"""

import json
from pathlib import Path


# ── HTML template (no f-string; placeholders swapped via .replace()) ──────────
_HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Research Intelligence — ENSO Tracker</title>
<style>
/* ── Tokens (dark-only, intentional: matches the rest of the site) ── */
:root {
  --bg:      #0d1117;
  --card:    #161b22;
  --card2:   #1c2128;
  --border:  #30363d;
  --text:    #c9d1d9;
  --muted:   #8b949e;
  --accent:  #58a6ff;
  --el:      #ef5350;
  --la:      #1e88e5;
  --lit:     #58a6ff;
  --news:    #f0883e;
  --warn:    #e3b341;
  --warn-bg: rgba(227,179,65,.12);
  --warn-bd: rgba(227,179,65,.28);
  --mono:    'SF Mono','Fira Code','Cascadia Code',monospace;
}

*,::before,::after { box-sizing: border-box; margin: 0; }
body {
  font-family: system-ui, -apple-system, sans-serif;
  background: var(--bg);
  color: var(--text);
  font-size: .9rem;
  line-height: 1.6;
  min-height: 100vh;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
strong { color: var(--text); font-weight: 600; }

/* ── Nav ── */
.topnav {
  display: flex; align-items: center; justify-content: space-between;
  padding: .6rem 1.2rem;
  border-bottom: 1px solid var(--border);
  background: var(--card);
  position: sticky; top: 0; z-index: 100;
  gap: .5rem; flex-wrap: wrap;
}
.nav-brand { font-weight: 700; font-size: .95rem; color: var(--text); text-decoration: none; }
.nav-links  { display: flex; gap: .4rem; flex-wrap: wrap; }
.nav-links a {
  color: var(--muted); text-decoration: none; font-size: .82rem;
  padding: .3rem .6rem; border-radius: 4px;
}
.nav-links a:hover      { color: var(--text); background: var(--card2); }
.nav-links a.nav-active { color: #fff; background: #f5a623; font-weight: 600; }

/* ── Page header ── */
.page-head { max-width: 1100px; margin: 0 auto; padding: 2rem 1.2rem 1.25rem; }
.page-head h1 {
  font-size: 1.4rem; font-weight: 700; color: var(--text);
  margin-bottom: .4rem; text-wrap: balance;
}
.page-meta {
  display: flex; flex-wrap: wrap; gap: .6rem 1rem;
  font-size: .78rem; font-family: var(--mono); color: var(--muted);
  margin-bottom: 1.1rem;
}
.meta-lit  { color: var(--lit); }
.meta-news { color: var(--news); }

/* ── View toggle ── */
.vtog-wrap { display: inline-flex; border: 1px solid var(--border); border-radius: 6px; overflow: hidden; margin-bottom: 1.4rem; }
.vtog-btn {
  background: var(--card2); color: var(--muted); border: none;
  padding: .42rem .9rem; font-size: .82rem; font-family: inherit;
  cursor: pointer; border-right: 1px solid var(--border); transition: background .13s, color .13s;
}
.vtog-btn:last-child { border-right: none; }
.vtog-btn.active    { background: var(--accent); color: #0d1117; font-weight: 600; }
.vtog-btn:hover:not(.active) { background: var(--card); color: var(--text); }
.vtog-btn:focus-visible { outline: 2px solid var(--accent); outline-offset: -2px; }

/* ── Detail view ── */
#view-detail {
  max-width: 1100px; margin: 0 auto;
  padding: 0 1.2rem 3rem;
  display: flex; flex-direction: column; gap: 1.25rem;
}

/* ── Category card ── */
.cat-card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow: hidden;
}

/* Provenance stripe — edge-to-edge, 8 px, above all padding */
.prov-stripe { height: 8px; display: flex; width: 100%; flex-shrink: 0; }
.prov-lit-seg  { background: var(--lit); }
.prov-news-seg { background: var(--news); }

.card-body { padding: 1.1rem 1.25rem; }

.card-top {
  display: flex; align-items: flex-start;
  justify-content: space-between; gap: .6rem;
  margin-bottom: .5rem; flex-wrap: wrap;
}
.cat-label { font-size: 1rem; font-weight: 700; color: var(--text); }

.conf-badge {
  font-size: .7rem; font-family: var(--mono);
  background: var(--warn-bg); color: var(--warn);
  border: 1px solid var(--warn-bd); border-radius: 4px;
  padding: .18rem .48rem; white-space: nowrap; flex-shrink: 0;
}

.prov-legend {
  display: flex; gap: .85rem; flex-wrap: wrap;
  font-size: .74rem; font-family: var(--mono); margin-bottom: .85rem;
}
.pleg-lit  { color: var(--lit);  }
.pleg-lit::before  { content: "● "; }
.pleg-news { color: var(--news); }
.pleg-news::before { content: "● "; }

/* ── Event tabs ── */
.event-tabs { display: flex; gap: .3rem; flex-wrap: wrap; margin-bottom: .85rem; }
.tab-btn {
  background: var(--card2); color: var(--muted);
  border: 1px solid var(--border); border-radius: 4px;
  padding: .28rem .62rem; font-size: .76rem; font-family: var(--mono);
  cursor: pointer; transition: background .12s, color .12s, border-color .12s;
}
.tab-btn:hover:not(.active) { color: var(--text); border-color: var(--muted); }
.tab-btn:focus-visible { outline: 2px solid var(--accent); }

/* current event → El Niño red; historical → accent blue */
.tab-btn.active[data-key="current_2026"]        { background: var(--el);     border-color: var(--el);     color: #fff; font-weight: 600; }
.tab-btn.active[data-key="1982_83"],
.tab-btn.active[data-key="1997_98"],
.tab-btn.active[data-key="2015_16"]             { background: var(--accent); border-color: var(--accent); color: #0d1117; font-weight: 600; }

/* ── Synthesis ── */
.synthesis-wrap { font-size: .875rem; line-height: 1.72; margin-bottom: .75rem; }
.synth-p        { margin-bottom: .55rem; color: var(--text); }
.synth-p:last-child { margin-bottom: 0; }
.synth-ol {
  margin: .35rem 0 .55rem 1.35rem;
  display: flex; flex-direction: column; gap: .28rem;
}
.synth-ol li { color: var(--text); }

/* ── Citation buttons ── */
.cite-btn {
  display: inline;
  background: none; border: none;
  color: var(--accent); font-family: var(--mono); font-size: .76rem;
  cursor: pointer; padding: 0 .08rem; border-radius: 2px;
  text-decoration: underline dotted; text-underline-offset: 2px;
}
.cite-btn:hover        { background: rgba(88,166,255,.12); text-decoration: underline; }
.cite-btn:focus-visible { outline: 2px solid var(--accent); }

/* ── Citation popup ── */
.cite-popup {
  background: var(--card2); border: 1px solid var(--accent);
  border-radius: 6px; padding: .65rem .85rem; margin: .45rem 0 .35rem;
  animation: popIn .12s ease;
}
@keyframes popIn {
  from { opacity: 0; transform: translateY(-4px); }
  to   { opacity: 1; transform: translateY(0); }
}
.cite-inner { display: flex; align-items: flex-start; gap: .6rem; }
.cite-icon  { font-size: .95rem; flex-shrink: 0; line-height: 1.5; }
.cite-info  { flex: 1; min-width: 0; }
.cite-title {
  font-weight: 600; color: var(--text); font-size: .82rem;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  margin-bottom: .18rem;
}
.cite-meta  { color: var(--muted); font-family: var(--mono); font-size: .72rem; }
.cite-link {
  flex-shrink: 0; align-self: center;
  color: var(--accent); font-size: .75rem; font-family: var(--mono);
  border: 1px solid var(--border); border-radius: 4px;
  padding: .18rem .42rem; white-space: nowrap;
  text-decoration: none; transition: background .12s;
}
.cite-link:hover { background: rgba(88,166,255,.1); text-decoration: none; }

/* ── Sources accordion ── */
.sources-details { margin-top: .4rem; }
.sources-summary {
  color: var(--muted); font-size: .78rem; font-family: var(--mono);
  cursor: pointer; padding: .3rem 0; list-style: none; user-select: none;
}
.sources-summary::-webkit-details-marker { display: none; }
.sources-summary::before         { content: "▸ "; }
details[open] .sources-summary::before { content: "▾ "; }

.sources-list {
  display: flex; flex-direction: column; gap: .3rem; padding-top: .45rem;
}
.src-item {
  display: flex; align-items: flex-start; gap: .45rem;
  padding: .4rem .5rem;
  background: var(--card2); border: 1px solid var(--border); border-radius: 5px;
  color: var(--text); text-decoration: none; font-size: .79rem;
  transition: border-color .12s;
}
.src-item:hover { border-color: var(--accent); }
.src-icon { font-size: .88rem; flex-shrink: 0; line-height: 1.45; }
.src-id   { font-family: var(--mono); color: var(--muted); font-size: .72rem; flex-shrink: 0; white-space: nowrap; }
.src-body { flex: 1; min-width: 0; }
.src-title { display: block; color: var(--text); font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.src-meta  { display: block; color: var(--muted); font-family: var(--mono); font-size: .7rem; margin-top: .08rem; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

/* ── Comparison view ── */
#view-compare {
  max-width: 1100px; margin: 0 auto;
  padding: 0 1.2rem 3rem;
  display: none; flex-direction: column; gap: 2rem;
}
.compare-row {}
.compare-cat-label {
  font-size: .76rem; font-weight: 700; font-family: var(--mono);
  text-transform: uppercase; letter-spacing: .07em; color: var(--muted);
  margin-bottom: .55rem;
}
.mini-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: .7rem;
}
@media (max-width: 800px) { .mini-grid { grid-template-columns: repeat(2,1fr); } }
@media (max-width: 480px) { .mini-grid { grid-template-columns: 1fr; } }

.mini-card {
  background: var(--card); border: 1px solid var(--border); border-radius: 7px;
  overflow: hidden; cursor: pointer;
  transition: border-color .15s, transform .13s;
}
.mini-card:hover { border-color: var(--accent); transform: translateY(-2px); }
.mini-card:focus-visible { outline: 2px solid var(--accent); }

.mini-stripe { height: 5px; display: flex; }
.mini-lit-seg  { background: var(--lit);  }
.mini-news-seg { background: var(--news); }

.mini-body { padding: .65rem .8rem; }
.mini-event-lbl {
  font-family: var(--mono); font-size: .7rem; font-weight: 700;
  margin-bottom: .18rem;
}
/* current → red; historical → blue */
.mini-card[data-evkey="current_2026"] .mini-event-lbl { color: var(--el); }
.mini-card[data-evkey="1982_83"]      .mini-event-lbl,
.mini-card[data-evkey="1997_98"]      .mini-event-lbl,
.mini-card[data-evkey="2015_16"]      .mini-event-lbl { color: var(--accent); }

.mini-counts { font-family: var(--mono); font-size: .67rem; color: var(--muted); margin-bottom: .35rem; }
.mini-excerpt {
  font-size: .77rem; color: var(--muted); line-height: 1.5;
  display: -webkit-box; -webkit-line-clamp: 4; -webkit-box-orient: vertical; overflow: hidden;
}
.mini-conf { font-family: var(--mono); font-size: .64rem; color: var(--warn); margin-top: .28rem; }

/* ── Footer ── */
.page-foot {
  max-width: 1100px; margin: 0 auto;
  padding: 1rem 1.2rem 2.5rem;
  font-size: .74rem; color: var(--muted);
  border-top: 1px solid var(--border);
}
.foot-lit  { color: var(--lit);  }
.foot-news { color: var(--news); }

/* ── Motion preference ── */
@media (prefers-reduced-motion: reduce) {
  .mini-card, .tab-btn, .vtog-btn, .cite-btn, .src-item { transition: none; }
  .cite-popup { animation: none; }
}
</style>
</head>
<body>

<nav class="topnav">
  <a class="nav-brand" href="index.html">ENSO Tracker</a>
  <div class="nav-links">
    <a href="index.html">ENSO Dashboard</a>
    <a href="hurricanes.html">Cyclones</a>
    <a href="precipitation.html">Precipitation</a>
    <a href="temperature.html">Temperature</a>
    <a href="sst.html">SST</a>
    <a href="impacts.html">Impacts</a>
    <a href="facts.html">Quick Facts</a>
    <a href="research.html" class="nav-active">Research</a>
  </div>
</nav>

<div class="page-head">
  <h1>ENSO Research Intelligence</h1>
  <div class="page-meta">
    <span><span class="meta-lit">●</span> __TOTAL_LIT__ literature chunks</span>
    <span><span class="meta-news">●</span> __TOTAL_NEWS__ news chunks</span>
    <span>__N_CATS__ domains · __N_EVENTS__ events: __EVENT_DISPLAYS__</span>
    <span>Generated __GENERATED__</span>
  </div>
  <div class="vtog-wrap">
    <button id="btn-detail" class="vtog-btn active">≡ Category Detail</button>
    <button id="btn-compare" class="vtog-btn">⊞ Event Comparison</button>
  </div>
</div>

<div id="view-detail"><p style="padding:2rem;color:var(--muted)">Building cards…</p></div>
<div id="view-compare"></div>

<footer class="page-foot">
  AI-synthesized via RAG pipeline &nbsp;·&nbsp;
  LLM: <span style="font-family:var(--mono)">__LLM_MODEL__</span> &nbsp;·&nbsp;
  Embeddings: <span style="font-family:var(--mono)">__EMBED_MODEL__</span>
  <br>Provenance stripes: <span class="foot-lit">■ peer-reviewed literature</span> &nbsp;
  <span class="foot-news">■ news reporting</span>
</footer>

<script>
const DATA = __DATA_JS__;

// ── Utilities ──────────────────────────────────────────────────────────────────

function esc(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function fmtDate(d) {
  if (!d) return '';
  try { return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' }); }
  catch (_) { return String(d).slice(0, 10); }
}

function provWidth(lit, news) {
  const t = (lit | 0) + (news | 0);
  return t === 0 ? 50 : Math.round(((lit | 0) / t) * 100);
}

function buildSourceMap(evData) {
  const m = {};
  for (const s of (evData.sources || [])) m[s.id] = s;
  return m;
}

// ── Citation regex ─────────────────────────────────────────────────────────────
// Patterns: [N0007], N0007 [event: ...], [0154]
const CITE_RE = /\[N(\d+)\]|N(\d+)\s*(?:\[event:[^\]]*\])?|\[0(\d+)\]/g;

function renderSynthesis(text, sourceMap) {
  // Step 1: citation patterns → clickable buttons (before markdown processing)
  let t = text.replace(CITE_RE, (match, g1, g2, g3) => {
    const id = g1 ? 'N' + g1 : g2 ? 'N' + g2 : '0' + (g3 || '');
    if (sourceMap[id]) {
      return '[<button class="cite-btn" data-id="' + esc(id) + '">' + esc(id) + '</button>]';
    }
    return match;
  });

  // Step 2: minimal markdown → HTML (bold, numbered lists, paragraphs)
  const lines = t.split('\n');
  let html = '', inList = false;
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      if (inList) { html += '</ol>'; inList = false; }
      continue;
    }
    const lm = line.match(/^(\d+)\.\s+([\s\S]+)$/);
    if (lm) {
      if (!inList) { html += '<ol class="synth-ol">'; inList = true; }
      html += '<li>' + boldify(lm[2]) + '</li>';
    } else {
      if (inList) { html += '</ol>'; inList = false; }
      html += '<p class="synth-p">' + boldify(line) + '</p>';
    }
  }
  if (inList) html += '</ol>';
  return html;
}

function boldify(s) {
  return s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

function buildCiteCard(src) {
  const academic = !!(src.journal || src.doi);
  const icon = academic ? '📄' : '📰';
  const meta = academic
    ? [src.journal, src.year, src.authors].filter(Boolean).join(' · ')
    : [src.source, fmtDate(src.published_date)].filter(Boolean).join(' · ');
  const lnk = src.url
    ? '<a class="cite-link" href="' + esc(src.url) + '" target="_blank" rel="noopener">Open →</a>'
    : '';
  return '<div class="cite-inner">'
    + '<span class="cite-icon">' + icon + '</span>'
    + '<div class="cite-info">'
    + '<div class="cite-title">' + esc(src.title || '') + '</div>'
    + '<div class="cite-meta">' + esc(meta) + '</div>'
    + '</div>' + lnk + '</div>';
}

function renderSourceItem(src) {
  const academic = !!(src.journal || src.doi);
  const icon = academic ? '📄' : '📰';
  const meta = academic
    ? [src.journal, src.year, src.authors].filter(Boolean).join(' · ')
    : [src.source, fmtDate(src.published_date)].filter(Boolean).join(' · ');
  const href = src.url ? ' href="' + esc(src.url) + '" target="_blank" rel="noopener"' : '';
  return '<a class="src-item"' + href + '>'
    + '<span class="src-icon">' + icon + '</span>'
    + '<span class="src-id">[' + esc(src.id) + ']</span>'
    + '<span class="src-body">'
    + '<span class="src-title">' + esc(src.title || '') + '</span>'
    + '<span class="src-meta">' + esc(meta) + '</span>'
    + '</span></a>';
}

// ── Citation popup ─────────────────────────────────────────────────────────────

let _citeKey    = null;
let _citePopup  = null;

function closeCitePopup() {
  if (_citePopup) { _citePopup.remove(); _citePopup = null; }
  _citeKey = null;
}

function attachCiteHandlers(wrap, sourceMap, domain) {
  wrap.querySelectorAll('.cite-btn').forEach(btn => {
    btn.addEventListener('click', e => {
      e.stopPropagation();
      const id  = btn.dataset.id;
      const key = id + ':' + domain;
      if (_citePopup) _citePopup.remove();
      if (_citeKey === key) { _citePopup = null; _citeKey = null; return; }
      _citeKey = key;
      const src = sourceMap[id];
      if (!src) return;
      const popup = document.createElement('div');
      popup.className = 'cite-popup';
      popup.innerHTML = buildCiteCard(src);
      const anchor = btn.closest('p.synth-p') || btn.closest('li') || btn.parentNode;
      anchor.insertAdjacentElement('afterend', popup);
      _citePopup = popup;
    });
  });
}

document.addEventListener('click', e => {
  if (!e.target.closest('.cite-btn') && !e.target.closest('.cite-popup')) closeCitePopup();
});

// ── Render event content into a card ──────────────────────────────────────────

function renderEventContent(card, cat, evKey, sourceMaps) {
  const evData    = cat.by_event[evKey];
  if (!evData) return;
  const sourceMap = sourceMaps[evKey] || {};

  // Synthesis
  const wrap = card.querySelector('.synthesis-wrap');
  wrap.innerHTML = renderSynthesis(evData.synthesis, sourceMap);
  attachCiteHandlers(wrap, sourceMap, cat.domain);

  // Sources
  const sources = evData.sources || [];
  card.querySelector('.src-count').textContent   = sources.length;
  card.querySelector('.sources-list').innerHTML  = sources.map(renderSourceItem).join('');

  // Provenance stripe + legend
  const lit  = evData.n_literature_chunks ?? 0;
  const news = evData.n_news_chunks ?? 0;
  const w    = provWidth(lit, news);
  card.querySelector('.prov-lit-seg').style.width  = w + '%';
  card.querySelector('.prov-news-seg').style.width = (100 - w) + '%';
  card.querySelector('.pleg-lit-val').textContent  = lit;
  card.querySelector('.pleg-news-val').textContent = news;

  // Confidence badge
  const badge = card.querySelector('.conf-badge');
  if (lit === 0 && !badge) {
    card.querySelector('.card-top').insertAdjacentHTML('beforeend',
      '<span class="conf-badge">current reporting only</span>');
  } else if (lit > 0 && badge) {
    badge.remove();
  }
}

// ── Build a detail card ────────────────────────────────────────────────────────

function buildDetailCard(cat) {
  const defaultKey = DATA.events[0].key;
  const defEv      = cat.by_event[defaultKey] || {};
  const lit0  = defEv.n_literature_chunks ?? 0;
  const news0 = defEv.n_news_chunks       ?? 0;
  const w0    = provWidth(lit0, news0);

  const sourceMaps = {};
  for (const ev of DATA.events) {
    if (cat.by_event[ev.key]) sourceMaps[ev.key] = buildSourceMap(cat.by_event[ev.key]);
  }

  const tabsHtml = DATA.events.map(ev =>
    '<button class="tab-btn' + (ev.key === defaultKey ? ' active' : '')
    + '" data-key="' + esc(ev.key) + '">' + esc(ev.display) + '</button>'
  ).join('');

  const badge0 = lit0 === 0 ? '<span class="conf-badge">current reporting only</span>' : '';

  const card = document.createElement('div');
  card.className    = 'cat-card';
  card.dataset.domain = cat.domain;

  card.innerHTML =
    '<div class="prov-stripe">'
    + '<div class="prov-lit-seg"  style="width:' + w0 + '%"></div>'
    + '<div class="prov-news-seg" style="width:' + (100 - w0) + '%"></div>'
    + '</div>'
    + '<div class="card-body">'
    + '<div class="card-top">'
    + '<span class="cat-label">' + esc(cat.label) + '</span>'
    + badge0
    + '</div>'
    + '<div class="prov-legend">'
    + '<span class="pleg-lit"><span class="pleg-lit-val">' + lit0 + '</span> peer-reviewed</span>'
    + '<span class="pleg-news"><span class="pleg-news-val">' + news0 + '</span> news</span>'
    + '</div>'
    + '<div class="event-tabs">' + tabsHtml + '</div>'
    + '<div class="synthesis-wrap"></div>'
    + '<details class="sources-details">'
    + '<summary class="sources-summary">Sources (<span class="src-count">0</span>)</summary>'
    + '<div class="sources-list"></div>'
    + '</details>'
    + '</div>';

  renderEventContent(card, cat, defaultKey, sourceMaps);

  card.querySelectorAll('.tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      closeCitePopup();
      card.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      const det = card.querySelector('details');
      if (det) det.removeAttribute('open');
      renderEventContent(card, cat, btn.dataset.key, sourceMaps);
    });
  });

  return card;
}

// ── Build comparison view ──────────────────────────────────────────────────────

function buildCompareView() {
  const container = document.getElementById('view-compare');
  container.innerHTML = '';

  for (const cat of DATA.categories) {
    const row = document.createElement('div');
    row.className = 'compare-row';

    const h3 = document.createElement('h3');
    h3.className   = 'compare-cat-label';
    h3.textContent = cat.label;
    row.appendChild(h3);

    const grid = document.createElement('div');
    grid.className = 'mini-grid';

    for (const ev of DATA.events) {
      const evData = cat.by_event[ev.key];
      if (!evData) continue;

      const lit  = evData.n_literature_chunks ?? 0;
      const news = evData.n_news_chunks       ?? 0;
      const w    = provWidth(lit, news);

      // Strip markdown and citations for clean excerpt
      const plain = evData.synthesis
        .replace(/\[N\d+\]|N\d+\s*(?:\[event:[^\]]*\])?|\[0\d+\]/g, '')
        .replace(/\*\*([^*]+)\*\*/g, '$1')
        .replace(/^\d+\.\s+/gm, '')
        .replace(/\n+/g, ' ')
        .trim();
      const excerpt = plain.length > 210 ? plain.slice(0, 207) + '…' : plain;

      const mini = document.createElement('div');
      mini.className      = 'mini-card';
      mini.dataset.evkey  = ev.key;
      mini.tabIndex       = 0;
      mini.setAttribute('role', 'button');
      mini.setAttribute('aria-label', ev.display + ' — ' + cat.label + '. Click to view detail.');

      mini.innerHTML =
        '<div class="mini-stripe">'
        + '<div class="mini-lit-seg"  style="width:' + w + '%"></div>'
        + '<div class="mini-news-seg" style="width:' + (100 - w) + '%"></div>'
        + '</div>'
        + '<div class="mini-body">'
        + '<div class="mini-event-lbl">' + esc(ev.display) + '</div>'
        + '<div class="mini-counts">' + lit + ' lit · ' + news + ' news</div>'
        + '<div class="mini-excerpt">' + esc(excerpt) + '</div>'
        + (lit === 0 ? '<div class="mini-conf">⚠ news only</div>' : '')
        + '</div>';

      function jumpToDetail(domain, evKey) {
        switchDetail();
        const target = document.querySelector('.cat-card[data-domain="' + domain + '"]');
        if (!target) return;
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        const tab = target.querySelector('.tab-btn[data-key="' + evKey + '"]');
        if (tab) tab.click();
      }

      mini.addEventListener('click', () => jumpToDetail(cat.domain, ev.key));
      mini.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); jumpToDetail(cat.domain, ev.key); }
      });

      grid.appendChild(mini);
    }

    row.appendChild(grid);
    container.appendChild(row);
  }
}

// ── View toggle ────────────────────────────────────────────────────────────────

function switchDetail() {
  document.getElementById('view-detail').style.display  = '';
  document.getElementById('view-compare').style.display = 'none';
  document.getElementById('btn-detail').classList.add('active');
  document.getElementById('btn-compare').classList.remove('active');
}

document.getElementById('btn-detail').addEventListener('click', switchDetail);
document.getElementById('btn-compare').addEventListener('click', () => {
  document.getElementById('view-detail').style.display  = 'none';
  document.getElementById('view-compare').style.display = 'flex';
  document.getElementById('btn-compare').classList.add('active');
  document.getElementById('btn-detail').classList.remove('active');
});

// ── Init ───────────────────────────────────────────────────────────────────────

const detailEl = document.getElementById('view-detail');
detailEl.innerHTML = '';
for (const cat of DATA.categories) detailEl.appendChild(buildDetailCard(cat));
buildCompareView();
</script>
</body>
</html>'''


def render_research(output_path: str = "docs/research.html") -> None:
    hist_path = Path("dashboard_historical.json")
    if not hist_path.exists():
        print("  [WARN] dashboard_historical.json not found — skipping research page")
        return

    with open(hist_path, encoding="utf-8") as f:
        hist = json.load(f)

    data_js     = json.dumps(hist, ensure_ascii=False, separators=(",", ":"))
    generated   = (hist.get("generated_at") or "")[:10]
    n_cats      = len(hist.get("categories", []))
    events      = hist.get("events", [])
    llm_model   = hist.get("llm_model", "")
    embed_model = hist.get("embed_model", "")

    total_lit = total_news = 0
    for cat in hist.get("categories", []):
        for evd in cat.get("by_event", {}).values():
            total_lit  += evd.get("n_literature_chunks", 0)
            total_news += evd.get("n_news_chunks",        0)

    event_displays = " · ".join(e["display"] for e in events)

    html = (
        _HTML
        .replace("__DATA_JS__",        data_js)
        .replace("__TOTAL_LIT__",      str(total_lit))
        .replace("__TOTAL_NEWS__",     str(total_news))
        .replace("__N_CATS__",         str(n_cats))
        .replace("__N_EVENTS__",       str(len(events)))
        .replace("__EVENT_DISPLAYS__", event_displays)
        .replace("__GENERATED__",      generated)
        .replace("__LLM_MODEL__",      llm_model)
        .replace("__EMBED_MODEL__",    embed_model)
    )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Research page → {output_path}")


if __name__ == "__main__":
    render_research()
