"""
render_impacts.py
Generates docs/impacts.html — ENSO Global Impacts page.
Reads docs/data/impacts_data.json (generated by fetch_impacts.py).
"""

import json
from pathlib import Path


def render_impacts(data: dict, output_path: str = "docs/impacts.html") -> None:
    data_js = json.dumps(data, separators=(",", ":"))

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ENSO Global Impacts</title>
<script src="https://cdn.plot.ly/plotly-2.30.0.min.js" charset="utf-8"></script>
<style>
  :root {{
    --bg:     #0d1117;
    --card:   #161b22;
    --border: #30363d;
    --text:   #c9d1d9;
    --muted:  #8b949e;
    --accent: hsl(265,75%,62%);
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text);
         font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
         padding: 1.5rem; }}
  .topnav {{ display:flex; align-items:center; justify-content:space-between;
             padding:.5rem 0; border-bottom:1px solid var(--border); margin-bottom:1.2rem; }}
  .nav-brand {{ font-weight:700; font-size:.95rem; color:var(--text); text-decoration:none; }}
  .nav-links {{ display:flex; gap:.4rem; flex-wrap:wrap; }}
  .nav-links a {{ color:var(--muted); text-decoration:none; font-size:.82rem;
                  padding:.3rem .7rem; border-radius:5px; }}
  .nav-links a:hover {{ color:var(--text); background:var(--card); }}
  .nav-links a.nav-active {{ color:#fff; background:#f5a623; font-weight:600; }}
  h1 {{ font-size:1.4rem; font-weight:700; margin-bottom:.2rem; }}
  .subtitle {{ color:var(--muted); font-size:.85rem; margin-bottom:1.5rem; }}
  .domain-card {{ background:var(--card); border:1px solid var(--border);
                  border-radius:8px; padding:1rem; margin-bottom:1.5rem; }}
  .domain-header {{ display:flex; align-items:baseline; justify-content:space-between;
                    flex-wrap:wrap; gap:.5rem; margin-bottom:.8rem; }}
  .domain-title {{ font-size:.78rem; text-transform:uppercase; letter-spacing:.05em;
                   color:var(--muted); }}
  .country-select {{ background:var(--bg); color:var(--text); border:1px solid var(--border);
                     border-radius:4px; padding:.25rem .5rem; font-size:.78rem; cursor:pointer; }}
  .corr-table {{ width:100%; font-size:.75rem; border-collapse:collapse; margin-top:.8rem; }}
  .corr-table th {{ color:var(--muted); text-align:left; padding:.25rem .5rem;
                    border-bottom:1px solid var(--border); font-weight:400; }}
  .corr-table td {{ padding:.25rem .5rem; border-bottom:1px solid #21262d; }}
  .corr-pos {{ color:#58a6ff; }}
  .corr-neg {{ color:#ef5350; }}
  .corr-weak {{ color:var(--muted); }}
  .legend-row {{ display:flex; gap:1.2rem; flex-wrap:wrap; margin:.5rem 0 0;
                 font-size:.73rem; color:var(--muted); align-items:center; }}
  .swatch {{ display:inline-block; width:14px; height:10px; border-radius:2px; margin-right:3px; }}
  .hatch-swatch {{ display:inline-block; width:14px; height:10px; border-radius:2px;
                   background:repeating-linear-gradient(45deg,#b8860033,#b8860033 2px,#b8860011 2px,#b8860011 6px);
                   border:1px solid #b8860066; margin-right:3px; }}
  .note {{ font-size:.73rem; color:var(--muted); margin-top:1rem; line-height:1.5; }}
  footer {{ font-size:.75rem; color:var(--muted); margin-top:1.5rem; text-align:center; }}
  footer a {{ color:var(--muted); }}
</style>
</head>
<body>

<nav class="topnav">
  <a class="nav-brand" href="index.html">ENSO Tracker</a>
  <div class="nav-links">
    <a href="index.html">Dashboard</a>
    <a href="hurricanes.html">Cyclones</a>
    <a href="precipitation.html">Precipitation</a>
    <a href="temperature.html">Temperature</a>
    <a href="sst.html">SST</a>
    <a href="impacts.html" class="nav-active">Impacts</a>
  </div>
</nav>

<h1>ENSO Global Impacts</h1>
<p class="subtitle">How El Niño &amp; La Niña correlate with economic growth, food production, commodity prices, and disasters — 1961–2024.
Lagged cross-correlations reported with and without major confound events (recessions, wars) highlighted in amber.</p>

<div class="legend-row">
  <span><span class="swatch" style="background:rgba(239,83,80,0.25)"></span>El Niño period</span>
  <span><span class="swatch" style="background:rgba(30,136,229,0.25)"></span>La Niña period</span>
  <span><span class="hatch-swatch"></span>Confound event (recession / war)</span>
  <span style="margin-left:.5rem">Bars: domain metric &nbsp;|&nbsp; Line: ONI (right axis)</span>
</div>

<!-- Domain panels injected by JS below -->
<div id="panels"></div>

<p class="note">
  <strong>Sources:</strong>
  ONI: <a href="https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt" target="_blank">NOAA/CPC</a> &nbsp;·&nbsp;
  GDP growth: <a href="https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG" target="_blank">World Bank</a> &nbsp;·&nbsp;
  Food Production Index: <a href="https://data.worldbank.org/indicator/AG.PRD.FOOD.XD" target="_blank">World Bank</a> &nbsp;·&nbsp;
  Food Price Index: <a href="https://www.fao.org/worldfoodsituation/foodpricesindex/en/" target="_blank">FAO</a><br>
  <strong>Method:</strong> Annual ONI average (12 overlapping 3-month seasons) vs. annual metric YoY change.
  Pearson &amp; Spearman correlations at lags 0–5 years, computed with and without confound-event years.
  A collapse in correlation when confound years are excluded suggests the correlation is driven by coincident macro shocks rather than ENSO.
</p>

<footer>
  Data updated: <span id="ts"></span> &nbsp;·&nbsp;
  <a href="https://github.com" target="_blank">GitHub</a>
</footer>

<script>
const D = {data_js};

// ── ENSO threshold helpers ────────────────────────────────────────────────────
function ensoPhase(oni) {{
  if (oni >=  0.5) return "el_nino";
  if (oni <= -0.5) return "la_nina";
  return "neutral";
}}

// Build ENSO shading shapes from annual ONI
function ensoShapes(oni_annual) {{
  const years = Object.keys(oni_annual).map(Number).sort((a,b)=>a-b);
  const shapes = [];
  let runStart = null, runPhase = null;
  for (const yr of years) {{
    const ph = ensoPhase(oni_annual[yr]);
    if (ph === runPhase) continue;
    if (runPhase && runPhase !== "neutral") {{
      shapes.push({{
        type:"rect", layer:"below", xref:"x", yref:"paper",
        x0: runStart - 0.5, x1: yr - 0.5, y0: 0, y1: 1,
        fillcolor: runPhase==="el_nino" ? "rgba(239,83,80,0.15)" : "rgba(30,136,229,0.15)",
        line: {{width:0}}
      }});
    }}
    runStart = yr; runPhase = ph;
  }}
  if (runPhase && runPhase !== "neutral") {{
    shapes.push({{
      type:"rect", layer:"below", xref:"x", yref:"paper",
      x0: runStart - 0.5, x1: years[years.length-1] + 0.5, y0: 0, y1: 1,
      fillcolor: runPhase==="el_nino" ? "rgba(239,83,80,0.15)" : "rgba(30,136,229,0.15)",
      line: {{width:0}}
    }});
  }}
  return shapes;
}}

// Build confound event shapes
function confoundShapes(events) {{
  return events.map(ev => ({{
    type:"rect", layer:"below", xref:"x", yref:"paper",
    x0: ev.start - 0.5, x1: ev.end + 0.5, y0: 0, y1: 1,
    fillcolor: "rgba(184,134,0,0.12)",
    line: {{color:"rgba(184,134,0,0.35)", width:1, dash:"dot"}}
  }}));
}}

// ── Plotly layout base ────────────────────────────────────────────────────────
const BG = "#0d1117", CARD = "#161b22", TEXT = "#c9d1d9", MUTED = "#8b949e", GRID = "#21262d";
function baseLayout(title, yLabel, xRange, shapes) {{
  return {{
    paper_bgcolor: CARD, plot_bgcolor: CARD,
    margin: {{t:32, r:60, b:40, l:55}},
    height: 220,
    font: {{color:TEXT, size:11}},
    title: {{text:title, font:{{size:12, color:TEXT}}, x:0, xanchor:"left", pad:{{l:2}}}},
    xaxis: {{
      range: xRange, gridcolor:GRID, zeroline:false,
      tickfont:{{size:10, color:MUTED}}, title:""
    }},
    yaxis: {{
      title:{{text:yLabel, font:{{size:10, color:MUTED}}}},
      gridcolor:GRID, zeroline:true, zerolinecolor:"#444",
      tickfont:{{size:10, color:MUTED}}
    }},
    yaxis2: {{
      title:{{text:"ONI (°C)", font:{{size:10, color:MUTED}}}},
      overlaying:"y", side:"right", zeroline:false, showgrid:false,
      tickfont:{{size:10, color:MUTED}}
    }},
    shapes: shapes,
    showlegend: true,
    legend: {{bgcolor:"rgba(0,0,0,0)", font:{{size:10, color:MUTED}},
              x:0, y:1.02, orientation:"h"}},
  }};
}}

function lagLayout(title) {{
  return {{
    paper_bgcolor: CARD, plot_bgcolor: CARD,
    margin: {{t:28, r:10, b:38, l:55}},
    height: 140,
    font: {{color:TEXT, size:10}},
    title: {{text:title, font:{{size:10, color:MUTED}}, x:0, xanchor:"left"}},
    xaxis: {{
      title:{{text:"Lag (years)", font:{{size:9, color:MUTED}}}},
      gridcolor:GRID, tickfont:{{size:9, color:MUTED}}, zeroline:false,
      tickvals:[0,1,2,3,4,5]
    }},
    yaxis: {{
      title:{{text:"Correlation", font:{{size:9, color:MUTED}}}},
      gridcolor:GRID, zeroline:true, zerolinecolor:"#555",
      tickfont:{{size:9, color:MUTED}}, range:[-1,1]
    }},
    barmode:"group",
    showlegend:true,
    legend:{{bgcolor:"rgba(0,0,0,0)", font:{{size:9, color:MUTED}},
             x:0, y:1.05, orientation:"h"}},
  }};
}}

// ── Color helpers ─────────────────────────────────────────────────────────────
const BAR_COLORS = {{
  pos: "rgba(88,166,255,0.7)", neg: "rgba(239,83,80,0.7)",
  neutral: "rgba(139,148,158,0.5)"
}};
function barColor(vals) {{
  return vals.map(v => v == null ? BAR_COLORS.neutral : (v >= 0 ? BAR_COLORS.pos : BAR_COLORS.neg));
}}

// ── Lag-correlation traces ────────────────────────────────────────────────────
function lagTraces(corrArr) {{
  const lags      = corrArr.map(c => c.lag);
  const p_full    = corrArr.map(c => c.full.pearson);
  const p_excl    = corrArr.map(c => c.excl.pearson);
  const s_full    = corrArr.map(c => c.full.spearman);
  const s_excl    = corrArr.map(c => c.excl.spearman);

  function barTrace(name, vals, color, dash) {{
    return {{
      type:"bar", name, x:lags, y:vals,
      marker:{{color:barColor(vals), line:{{width: dash ? 1 : 0, color:"#fff"}} }},
      opacity: dash ? 0.65 : 1,
      hovertemplate:"%{{y:.3f}}<extra>lag %{{x}}y</extra>"
    }};
  }}
  return [
    barTrace("Pearson (all years)",   p_full, null, false),
    barTrace("Pearson (excl. confounds)", p_excl, null, true),
    barTrace("Spearman (all years)",  s_full, null, false),
    barTrace("Spearman (excl. confounds)", s_excl, null, true),
  ];
}}

// ── Build a domain panel ──────────────────────────────────────────────────────
const ENSO_SHAPES    = ensoShapes(D.oni_annual);
const CONFOUND_SHAPES = confoundShapes(D.confound_events);
const ALL_SHAPES = [...CONFOUND_SHAPES, ...ENSO_SHAPES];

const oniYears  = Object.keys(D.oni_annual).map(Number).sort((a,b)=>a-b);
const oniValues = oniYears.map(y => D.oni_annual[y]);

function oniTrace(xRange) {{
  const ys = oniYears.filter(y => y >= xRange[0] && y <= xRange[1]);
  return {{
    type:"scatter", mode:"lines", name:"ONI",
    x:ys, y:ys.map(y=>D.oni_annual[y]),
    yaxis:"y2",
    line:{{color:"#f5a623", width:1.5}},
    hovertemplate:"ONI %{{x}}: %{{y:.2f}}°C<extra></extra>"
  }};
}}

function buildDomain(domKey, containerId) {{
  const dom = D.domains[domKey];
  if (!dom || !dom.countries) return;
  const countries = dom.countries;
  const isoList   = Object.keys(countries);
  if (!isoList.length) return;

  const container = document.getElementById(containerId);
  const tsId   = containerId + "_ts";
  const lagId  = containerId + "_lag";
  const selId  = containerId + "_sel";

  // Country selector
  const sel = container.querySelector("." + selId);
  isoList.forEach(iso => {{
    const opt = document.createElement("option");
    opt.value = iso;
    opt.textContent = countries[iso].name;
    sel.appendChild(opt);
  }});

  function plotCountry(iso) {{
    const c = countries[iso];
    const yrs = c.years, vals = c.values;
    const xRange = [Math.min(...yrs) - 1, Math.max(...yrs) + 1];
    const shapes  = ALL_SHAPES.filter(s => s.x0 >= xRange[0] - 2 && s.x1 <= xRange[1] + 2);
    const allShapes = [...CONFOUND_SHAPES, ...ensoShapes(D.oni_annual)];

    const barTrace = {{
      type:"bar", name: dom.label.split(" (")[0],
      x: yrs, y: vals,
      marker: {{color: barColor(vals)}},
      hovertemplate:"%{{x}}: %{{y:.2f}}<extra></extra>"
    }};

    const layout = baseLayout(
      dom.label + " — " + (countries[iso].name || iso),
      dom.label.split("(")[0].trim(),
      xRange, allShapes
    );

    Plotly.react(tsId, [barTrace, oniTrace(xRange)], layout, {{responsive:true, displayModeBar:false}});

    // Lag chart
    Plotly.react(lagId, lagTraces(c.corr),
      lagLayout("Lagged correlation: ONI → " + (countries[iso].name || iso)),
      {{responsive:true, displayModeBar:false}});

    // Correlation table
    const tbody = container.querySelector(".corr-tbody");
    tbody.innerHTML = "";
    c.corr.forEach(row => {{
      const tr = document.createElement("tr");
      function fmt(v) {{
        if (v == null) return '<td class="corr-weak">—</td>';
        const cls = Math.abs(v) < 0.1 ? "corr-weak" : (v >= 0 ? "corr-pos" : "corr-neg");
        return `<td class="${{cls}}">${{v.toFixed(3)}}</td>`;
      }}
      tr.innerHTML = `<td>${{row.lag}}y</td>
        <td>${{row.full.n}}</td>${{fmt(row.full.pearson)}}${{fmt(row.full.spearman)}}
        <td>${{row.excl.n}}</td>${{fmt(row.excl.pearson)}}${{fmt(row.excl.spearman)}}`;
      tbody.appendChild(tr);
    }});
  }}

  sel.addEventListener("change", () => plotCountry(sel.value));
  plotCountry(isoList[0]);
}}

// ── Render domain cards ───────────────────────────────────────────────────────
const DOMAIN_META = [
  {{ key:"gdp",        title:"Economic Growth",         icon:"📈",
     desc:"Annual GDP growth rate (%). El Niño is associated with reduced growth in tropical economies. Callahan &amp; Mankin (2023) found effects persisting 5+ years post-event." }},
  {{ key:"food_prod",  title:"Agricultural Production", icon:"🌾",
     desc:"Food Production Index year-over-year change. ENSO disrupts precipitation regimes, particularly affecting tropical grain and cereal yields." }},
  {{ key:"food_price", title:"Food Commodity Prices",   icon:"🛒",
     desc:"FAO Food Price Index year-over-year change. El Niño–driven droughts in major growing regions can spike global commodity prices with a 0–2 year lag." }},
  {{ key:"disasters",  title:"Natural Disasters",        icon:"🌪",
     desc:"Annual global disaster count from EM-DAT. El Niño intensifies floods, droughts, and cyclones across different regions simultaneously." }},
];

const panels = document.getElementById("panels");
DOMAIN_META.forEach(meta => {{
  const dom = D.domains[meta.key];
  const hasData = dom && dom.countries;
  const cid = "dom_" + meta.key;

  const card = document.createElement("div");
  card.className = "domain-card";
  card.id = cid;
  card.innerHTML = `
    <div class="domain-header">
      <span class="domain-title">${{meta.icon}} ${{meta.title}}</span>
      ${{hasData
          ? `<select class="country-select ${{cid}}_sel"></select>`
          : `<span style="font-size:.75rem;color:var(--muted)">No data — upload EM-DAT CSV to docs/data/emdat.csv</span>`
      }}
    </div>
    <p style="font-size:.75rem;color:var(--muted);margin-bottom:.6rem">${{meta.desc}}</p>
    ${{hasData ? `
      <div id="${{cid}}_ts"></div>
      <div id="${{cid}}_lag" style="margin-top:.4rem"></div>
      <table class="corr-table" style="margin-top:.6rem">
        <thead><tr>
          <th>Lag</th>
          <th colspan="3" style="border-left:1px solid var(--border);padding-left:.5rem">All years</th>
          <th colspan="3" style="border-left:1px solid var(--border);padding-left:.5rem">Excl. confounds</th>
        </tr><tr>
          <th></th><th>n</th><th>Pearson r</th><th>Spearman ρ</th>
          <th style="border-left:1px solid var(--border)">n</th><th>Pearson r</th><th>Spearman ρ</th>
        </tr></thead>
        <tbody class="corr-tbody"></tbody>
      </table>` : ``
    }}
  `;
  panels.appendChild(card);
  if (hasData) buildDomain(meta.key, cid);
}});

document.getElementById("ts").textContent = new Date(D.generated).toLocaleDateString();
</script>
</body>
</html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    print(f"Rendered → {output_path}")


def main() -> None:
    data_path = Path("docs/data/impacts_data.json")
    if not data_path.exists():
        raise FileNotFoundError(
            f"{data_path} not found — run fetch_impacts.py first"
        )
    with open(data_path) as f:
        data = json.load(f)
    render_impacts(data)


if __name__ == "__main__":
    main()
